steps:
  - command: "echo python .buildkite/pipeline.py && python .buildkite/pipeline.py | buildkite-agent pipeline upload"
    label: ":rocket:"
    agents:
    - "macos=true"

  - wait

  - command: "echo \"DONE!\""